// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuwuuarxodkyzvjiiksu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1d3V1YXJ4b2RreXp2amlpa3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTc1MzIsImV4cCI6MjA2MDIzMzUzMn0.ZxiW9QQOaZ62JuUhZFcTBJ2BFTW7s6YcG8wNCutyxbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);